# Generated by Django 6.0.3 on 2026-03-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('intent', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('BOTH', 'Both')], default='BOTH', help_text="User's primary intent on the platform.", max_length=4)),
                ('classification', models.CharField(blank=True, choices=[('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophomore'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], help_text="User's academic classification.", max_length=10, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text='The user who referred this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='waitlist.waitlistentry')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
            },
        ),
    ]
