# Generated by Django 6.0.3 on 2026-03-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
